from django.contrib import admin
from .models import *

admin.site.register(Company)
admin.site.register(Building)
admin.site.register(Floor)
admin.site.register(Department)
admin.site.register(JobPosition)
admin.site.register(Model)
admin.site.register(ContractType)
admin.site.register(Employees)
admin.site.register(LeavesRequest)
admin.site.register(InsuranceRenewals)
admin.site.register(SalaryStructures)
admin.site.register(CreateContracts)
admin.site.register(SalaryRules)
admin.site.register(EmployeePayslip)
admin.site.register(Announcements)
admin.site.register(Plan)
admin.site.register(Appraisal)
admin.site.register(AnswerAppraisal)
admin.site.register(Contact)
admin.site.register(ContactTags)
admin.site.register(contactTitles)
admin.site.register(ContactIndustry)
admin.site.register(createBanks)
admin.site.register(CreateBankAC)
admin.site.register(createPublicChannel)
admin.site.register(allowanceToGrant)
admin.site.register(CreateBadges)
admin.site.register(DisplayMode)
admin.site.register(CreateChallenge)
admin.site.register(Project)
admin.site.register(LeaveType)
admin.site.register(PayslipBatch)
admin.site.register(JobTitle)
admin.site.register(EmployementGrades)
admin.site.register(EmployementLevel)
admin.site.register(allowances)
admin.site.register(deductionAddition)
admin.site.register(bank)
admin.site.register(insurance)
admin.site.register(holidays)
admin.site.register(costcenter)
admin.site.register(location)
admin.site.register(documentType)
admin.site.register(custodytype)
admin.site.register(brands)
admin.site.register(brandModel)


