# Generated by Django 3.2.11 on 2024-12-11 16:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='memos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationIcon', models.CharField(blank=True, choices=[('Info', 'Info'), ('Check', 'Check'), ('Warning', 'Warning'), ('Danger', 'Danger')], max_length=50, null=True)),
                ('titleAR', models.CharField(blank=True, max_length=500, null=True)),
                ('titleEN', models.CharField(blank=True, max_length=500, null=True)),
                ('bodyAR', models.CharField(blank=True, max_length=5000, null=True)),
                ('bodyEN', models.CharField(blank=True, max_length=5000, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('date', models.DateField(default=datetime.date.today)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employees')),
            ],
        ),
    ]
