# Generated by Django 3.2.3 on 2021-07-01 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.CharField(max_length=1000)),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='')),
                ('doctype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.documenttype')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=250)),
                ('handover', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('Return', 'Return'), ('Active', 'Active')], max_length=250)),
                ('returndate', models.DateField()),
                ('description', models.CharField(max_length=1000)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employees')),
            ],
        ),
    ]
