# Generated by Django 3.1.2 on 2020-12-22 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='allowanceToGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Everyone', models.BooleanField(default=False)),
                ('SelectedListOfUsers', models.BooleanField(default=False)),
                ('PeopleHavingSomeBadges', models.BooleanField(default=False)),
                ('NoOneAssignedThroughChallenges', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerAppraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.BooleanField(default=False)),
                ('creationDate', models.DateField(default=django.utils.timezone.now)),
                ('deadline', models.DateField(default=django.utils.timezone.now)),
                ('partner', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('answerType', models.CharField(choices=[('1', 'Manually'), ('2', 'Automatically')], max_length=250)),
                ('status', models.CharField(choices=[('1', 'Completed'), ('2', 'Partially Completed'), ('3', 'Not Started Yet')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingName', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250)),
                ('Address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=250)),
                ('Company_Tagline', models.CharField(max_length=250)),
                ('Address1', models.CharField(max_length=250)),
                ('Address2', models.CharField(max_length=250)),
                ('Pin_code', models.IntegerField()),
                ('State', models.CharField(max_length=250)),
                ('City', models.CharField(max_length=250)),
                ('Website', models.URLField()),
                ('Email', models.EmailField(max_length=254)),
                ('Tin', models.CharField(max_length=150)),
                ('Company_registry', models.CharField(max_length=250)),
                ('Currency', models.CharField(max_length=250)),
                ('Reportfooter', models.CharField(max_length=250)),
                ('Twitter', models.CharField(max_length=150)),
                ('Facebook', models.CharField(max_length=150)),
                ('Git', models.CharField(max_length=150)),
                ('Linkedin', models.CharField(max_length=150)),
                ('Phone', models.CharField(max_length=150)),
                ('Partner', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ContactIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industryName', models.CharField(max_length=500)),
                ('fullName', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContactTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=False)),
                ('parentCategory', models.CharField(choices=[('1', 'Manufacturer'), ('2', 'Other')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='contactTitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abbreviation', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='createBanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BankName', models.CharField(max_length=500)),
                ('BankIdentifierCode', models.CharField(max_length=500)),
                ('address1', models.CharField(max_length=500)),
                ('address2', models.CharField(max_length=500)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CreateContracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractsReference', models.CharField(max_length=250)),
                ('Wage', models.CharField(max_length=250)),
                ('Trail_Period_Duration_From', models.DateField(default=django.utils.timezone.now)),
                ('Trail_Period_Duration_T0', models.DateField(default=django.utils.timezone.now)),
                ('Duration_From', models.DateField(default=django.utils.timezone.now)),
                ('Duration_To', models.DateField(default=django.utils.timezone.now)),
                ('Scheduled_Pay', models.CharField(max_length=250)),
                ('Date_From', models.DateField(default=django.utils.timezone.now)),
                ('Date_To', models.DateField(default=django.utils.timezone.now)),
                ('Shift', models.CharField(max_length=250)),
                ('Contract_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contracttype')),
            ],
        ),
        migrations.CreateModel(
            name='createPublicChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelName', models.CharField(max_length=500)),
                ('SendMessagesByEmail', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DisplayMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IndividualGoals', models.BooleanField(default=False)),
                ('LeaderBoard', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Working_Address', models.CharField(max_length=250)),
                ('Work_Location', models.CharField(max_length=250)),
                ('Work_Email', models.EmailField(max_length=254)),
                ('Work_Mobile', models.CharField(max_length=250)),
                ('Work_Phone', models.IntegerField()),
                ('Manager', models.CharField(max_length=250)),
                ('Coach', models.CharField(max_length=250)),
                ('Working_hours', models.CharField(max_length=250)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.BooleanField(default=False)),
                ('employee', models.BooleanField(default=False)),
                ('collaborators', models.BooleanField(default=False)),
                ('colleague', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Description', models.CharField(max_length=5000)),
                ('Manager', models.CharField(max_length=500)),
                ('Reference', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStructures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Parent', models.CharField(max_length=250)),
                ('Salary_Advance_After_Days', models.IntegerField()),
                ('Reference', models.CharField(max_length=250)),
                ('Max_Salary_Advance_Percentage', models.IntegerField()),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Company')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Category', models.CharField(max_length=250)),
                ('Code', models.CharField(max_length=250)),
                ('Active', models.BooleanField(default=False)),
                ('Sequence', models.IntegerField()),
                ('AppearsOnPayslip', models.BooleanField(default=False)),
                ('ConditionBasedOn', models.CharField(choices=[('1', ''), ('2', 'Other')], max_length=300)),
                ('AmountType', models.CharField(choices=[('1', 'Fixed Amount'), ('2', 'Other')], max_length=300)),
                ('Quantity', models.IntegerField()),
                ('FixedAmount', models.IntegerField()),
                ('Contribution_Register', models.CharField(max_length=250)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Company')),
            ],
        ),
        migrations.CreateModel(
            name='LeavesRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=250)),
                ('Leave_Type', models.CharField(choices=[('1', 'sick leave'), ('2', 'two')], max_length=250)),
                ('Duration_From', models.DateTimeField(default=django.utils.timezone.now)),
                ('Duration_To', models.DateTimeField(default=django.utils.timezone.now)),
                ('Duration_Days', models.CharField(max_length=250)),
                ('Mode', models.CharField(max_length=250)),
                ('Reported_in_last_payslips', models.CharField(max_length=250)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Company')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employees')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceRenewals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Search_by', models.CharField(max_length=250)),
                ('Start_Date', models.DateField(default=django.utils.timezone.now)),
                ('End_Date', models.DateField(default=django.utils.timezone.now)),
                ('Remainder_Before', models.IntegerField()),
                ('Remainder_Expiry_Date', models.DateField(default=django.utils.timezone.now)),
                ('Active', models.BooleanField()),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Company')),
                ('Field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.field')),
                ('Model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.model')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='Job_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.jobposition'),
        ),
        migrations.AddField(
            model_name='employees',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmployeePayslip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Period_From', models.DateField(default=django.utils.timezone.now)),
                ('Period_To', models.DateField(default=django.utils.timezone.now)),
                ('Reference', models.CharField(max_length=250)),
                ('PaySlip_Name', models.CharField(max_length=250)),
                ('Leave_Salary', models.BooleanField(max_length=250)),
                ('Credit_Note', models.BooleanField(default=False)),
                ('Description', models.CharField(max_length=250)),
                ('Code', models.CharField(max_length=250)),
                ('Number_Of_Days', models.CharField(max_length=250)),
                ('Number_Of_Hours', models.CharField(max_length=250)),
                ('Contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.createcontracts')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employees')),
                ('Structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.salarystructures')),
            ],
        ),
        migrations.AddField(
            model_name='createcontracts',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department'),
        ),
        migrations.AddField(
            model_name='createcontracts',
            name='Employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employees'),
        ),
        migrations.AddField(
            model_name='createcontracts',
            name='Job_Position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.jobposition'),
        ),
        migrations.AddField(
            model_name='createcontracts',
            name='Salary_Structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.salarystructures'),
        ),
        migrations.CreateModel(
            name='CreateContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual', models.BooleanField(default=False)),
                ('Company', models.BooleanField(default=False)),
                ('Employee', models.CharField(max_length=300)),
                ('address1', models.CharField(max_length=5000)),
                ('address2', models.CharField(max_length=5000)),
                ('pincode', models.IntegerField()),
                ('country', models.CharField(max_length=5000)),
                ('tin', models.IntegerField()),
                ('jobPosition', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('title', models.CharField(choices=[('1', 'Mr.'), ('2', 'Ms.'), ('3', 'Mrs.')], max_length=250)),
                ('language', models.CharField(choices=[('1', 'English'), ('2', 'Urdu'), ('3', 'other')], max_length=250)),
                ('companyContact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CreateChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChallengeName', models.CharField(max_length=500)),
                ('AssignChallengeTo', models.CharField(max_length=500)),
                ('Periodicity', models.CharField(choices=[('1', 'daily'), ('2', 'Other')], max_length=500)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('DisplayMode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.displaymode')),
                ('Responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employees')),
            ],
        ),
        migrations.CreateModel(
            name='CreateBankAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNo', models.CharField(max_length=5000)),
                ('ABA_Routing', models.CharField(max_length=5000)),
                ('currency', models.CharField(max_length=500)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.createbanks')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CreateBadges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BadgeTitle', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=5000)),
                ('MonthlyLimitedSending', models.BooleanField(default=False)),
                ('MyMonthlySendingTotal', models.CharField(max_length=500)),
                ('AllownaceToGrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.allowancetogrant')),
            ],
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appraisal_deadline', models.DateField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employees')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_general_announcements', models.BooleanField(default=False)),
                ('code_no', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=5000)),
                ('Attachment', models.FileField(upload_to='')),
                ('requestedDate', models.DateField(default=django.utils.timezone.now)),
                ('letter', models.CharField(max_length=10000)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Company')),
            ],
        ),
    ]
