# Generated by Django 3.1.4 on 2020-12-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201223_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=500),
        ),
    ]
