# Generated by Django 3.1.2 on 2020-12-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201223_1214'),
        ('home', '0003_auto_20201223_1159'),
    ]

    operations = [
    ]
