# Generated by Django 3.1.2 on 2020-12-24 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_merge_20201224_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.floor'),
        ),
        migrations.AddField(
            model_name='floor',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.building'),
        ),
    ]
