# Generated by Django 3.1.2 on 2020-12-28 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201228_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createcontact',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='createcontact',
            name='individual',
        ),
    ]
