# Generated by Django 3.1.4 on 2020-12-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201228_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Company',
            name='Company_registry',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='Company',
            name='Currency',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='Company',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='Company',
            name='Facebook',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='Company',
            name='Git',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='Company',
            name='Linkedin',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='Company',
            name='Partner',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='Company',
            name='Phone',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='Company',
            name='Reportfooter',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='Company',
            name='Tin',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='Company',
            name='Twitter',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='Company',
            name='Website',
            field=models.URLField(null=True),
        ),
    ]
