# Generated by Django 3.1.2 on 2020-12-29 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201229_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address1', models.CharField(max_length=5000)),
                ('address2', models.CharField(max_length=5000)),
                ('pincode', models.IntegerField()),
                ('country', models.CharField(max_length=5000)),
                ('tin', models.IntegerField()),
                ('jobPosition', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('title', models.CharField(choices=[('1', 'Mr.'), ('2', 'Ms.'), ('3', 'Mrs.')], max_length=250)),
                ('language', models.CharField(choices=[('1', 'English'), ('2', 'Urdu'), ('3', 'other')], max_length=250)),
                ('companyContact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Company')),
            ],
        ),
        migrations.DeleteModel(
            name='CreateContact',
        ),
    ]
