# Generated by Django 3.1.4 on 2021-01-02 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_auto_20201230_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavesrequest',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='leavesrequest',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='leavesrequest',
            name='Employee',
        ),
        migrations.AddField(
            model_name='leavesrequest',
            name='CommentbyManager',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavesrequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Override', models.BooleanField(default=False)),
                ('Limit', models.IntegerField()),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Company')),
            ],
        ),
        migrations.AlterField(
            model_name='leavesrequest',
            name='Leave_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.leavetype'),
        ),
    ]
