# Generated by Django 3.1.4 on 2021-01-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210102_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavesrequest',
            name='Mode',
        ),
    ]
