# Generated by Django 3.1.4 on 2021-01-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_leavesrequest_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavesrequest',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Approved'), ('2', 'Rejected')], default=1, max_length=500),
            preserve_default=False,
        ),
    ]
