# Generated by Django 3.1.4 on 2021-01-02 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_leavesrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavesrequest',
            name='CommentbyManager',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='leavesrequest',
            name='Description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='leavesrequest',
            name='Duration_Days',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='leavesrequest',
            name='Leave_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.leavetype'),
        ),
        migrations.AlterField(
            model_name='leavesrequest',
            name='Reported_in_last_payslips',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='leavesrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'Approved'), ('2', 'Rejected')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='leavesrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='Override',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='Title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Company'),
        ),
    ]
