# Generated by Django 3.1.4 on 2021-01-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210102_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavesrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=500, null=True),
        ),
    ]
