# Generated by Django 3.1.4 on 2021-01-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210110_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='Override',
            field=models.BooleanField(),
        ),
    ]
