# Generated by Django 3.1.4 on 2021-01-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210110_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='Override',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
