# Generated by Django 3.1.4 on 2021-01-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210110_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSalaryLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
            ],
        ),
    ]
