# Generated by Django 3.1.4 on 2021-01-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_requestsalaryletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='isHr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employees',
            name='isManager',
            field=models.BooleanField(default=False),
        ),
    ]
