# Generated by Django 3.1.4 on 2021-01-16 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210115_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavesrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.employees'),
        ),
    ]
