# Generated by Django 3.1.4 on 2021-01-17 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210116_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcontracts',
            name='Salary_Structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.salarystructures'),
        ),
    ]
