# Generated by Django 3.1.4 on 2021-01-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20210117_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcontracts',
            name='Stage',
            field=models.CharField(choices=[('1', 'New'), ('2', 'Running'), ('3', 'To Renew'), ('4', 'Expired'), ('5', 'Cancelled')], default=1, max_length=250),
            preserve_default=False,
        ),
    ]
