# Generated by Django 3.1.4 on 2021-01-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20210117_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createcontracts',
            name='Trail_Period_Duration_From',
        ),
        migrations.RemoveField(
            model_name='createcontracts',
            name='Trail_Period_Duration_T0',
        ),
        migrations.AddField(
            model_name='createcontracts',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
