# Generated by Django 3.1.4 on 2021-01-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20210117_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createcontracts',
            name='Scheduled_Pay',
        ),
    ]
