# Generated by Django 3.1.5 on 2021-02-02 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20210126_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createcontracts',
            name='Duration_From',
        ),
        migrations.RemoveField(
            model_name='createcontracts',
            name='Duration_To',
        ),
        migrations.RemoveField(
            model_name='createcontracts',
            name='Salary_Structure',
        ),
        migrations.RemoveField(
            model_name='createcontracts',
            name='Shift',
        ),
        migrations.RemoveField(
            model_name='createcontracts',
            name='Wage',
        ),
        migrations.RemoveField(
            model_name='createcontracts',
            name='file',
        ),
        migrations.AddField(
            model_name='createcontracts',
            name='GOSI',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='createcontracts',
            name='Housing_Allowance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='createcontracts',
            name='base_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='createcontracts',
            name='breakhours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='createcontracts',
            name='shift_end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='createcontracts',
            name='shift_start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='createcontracts',
            name='workinghours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='createcontracts',
            name='Contract_Type',
            field=models.CharField(choices=[('1', 'Full Time'), ('2', 'Contract')], default=1, max_length=250),
            preserve_default=False,
        ),
    ]
