# Generated by Django 3.1.5 on 2021-02-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20210202_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcontracts',
            name='shift_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='createcontracts',
            name='shift_start',
            field=models.TimeField(),
        ),
    ]
