# Generated by Django 3.1.5 on 2021-02-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20210202_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcontracts',
            name='Contract_Type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Contract Basis', 'Contract Basis')], max_length=250),
        ),
    ]
