# Generated by Django 3.1.5 on 2021-02-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20210202_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcontracts',
            name='Transport_Allowance',
            field=models.IntegerField(default=0),
        ),
    ]
