# Generated by Django 3.1.5 on 2021-02-02 07:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_createcontracts_transport_allowance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayslipBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Period_From', models.DateField(default=datetime.datetime.now)),
                ('Period_To', models.DateField(default=datetime.datetime.now)),
                ('PaySlip_Name', models.CharField(max_length=500)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Company')),
            ],
        ),
    ]
