# Generated by Django 3.1.2 on 2021-02-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_payslipbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcontracts',
            name='contract_period',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createcontracts',
            name='employment_type',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createcontracts',
            name='notice_period',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createcontracts',
            name='probation_period',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='DOJ',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='employeenumber',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='nationalid',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='nationality',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='Job_position',
            field=models.CharField(max_length=250),
        ),
    ]
