# Generated by Django 3.1.2 on 2021-02-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20210206_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcontracts',
            name='otherallowance',
            field=models.IntegerField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
