# Generated by Django 3.1.5 on 2021-02-06 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20210206_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeepayslip',
            old_name='Code',
            new_name='earnings_as_per_workinghours',
        ),
        migrations.RenameField(
            model_name='employeepayslip',
            old_name='Description',
            new_name='no_of_working_hours',
        ),
        migrations.RemoveField(
            model_name='employeepayslip',
            name='Contract',
        ),
        migrations.RemoveField(
            model_name='employeepayslip',
            name='Credit_Note',
        ),
        migrations.RemoveField(
            model_name='employeepayslip',
            name='Leave_Salary',
        ),
        migrations.RemoveField(
            model_name='employeepayslip',
            name='Number_Of_Days',
        ),
        migrations.RemoveField(
            model_name='employeepayslip',
            name='Number_Of_Hours',
        ),
        migrations.RemoveField(
            model_name='employeepayslip',
            name='Period_From',
        ),
        migrations.RemoveField(
            model_name='employeepayslip',
            name='Period_To',
        ),
        migrations.RemoveField(
            model_name='employeepayslip',
            name='Reference',
        ),
        migrations.RemoveField(
            model_name='employeepayslip',
            name='Structure',
        ),
        migrations.AddField(
            model_name='employeepayslip',
            name='addition',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeepayslip',
            name='other_deductions',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeepayslip',
            name='tax',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeepayslip',
            name='total_earnings',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeepayslip',
            name='PaySlip_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.payslipbatch'),
        ),
    ]
