# Generated by Django 3.1.5 on 2021-02-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20210206_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepayslip',
            name='PaySlip_Name',
        ),
        migrations.RemoveField(
            model_name='employeepayslip',
            name='addition',
        ),
        migrations.RemoveField(
            model_name='employeepayslip',
            name='earnings_as_per_workinghours',
        ),
        migrations.RemoveField(
            model_name='employeepayslip',
            name='no_of_working_hours',
        ),
        migrations.RemoveField(
            model_name='employeepayslip',
            name='other_deductions',
        ),
        migrations.RemoveField(
            model_name='employeepayslip',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='employeepayslip',
            name='total_earnings',
        ),
    ]
