# Generated by Django 3.1.5 on 2021-02-06 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20210206_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayslip',
            name='PaySlip_Name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.payslipbatch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeepayslip',
            name='addition',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeepayslip',
            name='earnings_as_per_workinghours',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeepayslip',
            name='no_of_working_hours',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeepayslip',
            name='other_deductions',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeepayslip',
            name='tax',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeepayslip',
            name='total_earnings',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
