# Generated by Django 3.1.5 on 2021-02-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20210206_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='idtype',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
