# Generated by Django 3.1.5 on 2021-02-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_employees_idtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createcontracts',
            name='Job_Position',
        ),
    ]
