# Generated by Django 3.1.7 on 2021-03-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_remove_createcontracts_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='DOJ',
            field=models.DateField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='idtype',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='nationality',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
