# Generated by Django 3.1.7 on 2021-03-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20210318_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='DOJ',
            field=models.DateField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employeenumber',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='idtype',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='nationalid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='nationality',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
