# Generated by Django 3.1.7 on 2021-04-22 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_auto_20210318_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='Attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='is_general_announcements',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='requestedDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
