# Generated by Django 3.1.7 on 2021-04-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_auto_20210422_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='Attachment',
            field=models.FileField(default=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='requestedDate',
            field=models.DateField(default=False),
        ),
    ]
