# Generated by Django 3.1.7 on 2021-04-22 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_auto_20210422_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='Attachment',
            field=models.FileField(blank=True, default=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='requestedDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
