# Generated by Django 3.1.7 on 2021-04-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_auto_20210422_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='Attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
