# Generated by Django 3.1.7 on 2021-04-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_auto_20210422_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='Attachment',
        ),
    ]
