# Generated by Django 3.2 on 2021-04-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_remove_announcements_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavesrequest',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Approved'), ('3', 'Rejected')], default='Pending', max_length=500),
        ),
    ]
