# Generated by Django 3.2 on 2021-04-29 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_alter_leavesrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employees'),
        ),
    ]
