# Generated by Django 3.2 on 2021-05-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_alter_project_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='arFirstname',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='arLastname',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
