# Generated by Django 3.2 on 2021-05-01 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_auto_20210501_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='arFirstname',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='arLastname',
        ),
    ]
