# Generated by Django 3.2 on 2021-05-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_auto_20210501_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='ArTitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
