# Generated by Django 3.2 on 2021-05-09 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_leavetype_artitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='title',
            field=models.CharField(max_length=5000, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
