# Generated by Django 3.2.3 on 2021-06-14 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_allowances_bank_deductionaddition_employementgrades_employementlevel_jobtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Job_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.jobtitle'),
        ),
    ]
