# Generated by Django 3.2.3 on 2021-06-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_alter_employees_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Job_position',
            field=models.CharField(max_length=250),
        ),
    ]
