# Generated by Django 3.2.3 on 2021-06-17 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_auto_20210617_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employementgrades',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.company'),
        ),
        migrations.AlterField(
            model_name='employementlevel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.company'),
        ),
    ]
