# Generated by Django 3.2.3 on 2021-06-17 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_alter_employees_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.employementgrades'),
            preserve_default=False,
        ),
    ]
