# Generated by Django 3.2.3 on 2021-06-17 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_alter_employees_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employementgrades',
            name='company',
        ),
        migrations.AddField(
            model_name='employementgrades',
            name='jobtitle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.jobtitle'),
            preserve_default=False,
        ),
    ]
