# Generated by Django 3.2.3 on 2021-06-17 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_auto_20210617_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.employementlevel'),
            preserve_default=False,
        ),
    ]
