# Generated by Django 3.2.3 on 2021-06-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_auto_20210618_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='blonge',
            new_name='belong',
        ),
    ]
