# Generated by Django 3.2.3 on 2021-06-19 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_rename_blonge_department_belong'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttype',
            name='CompanyGOSIForNonSaudi',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contracttype',
            name='CompanyGOSIForSaudi',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contracttype',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contracttype',
            name='titleAr',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
