# Generated by Django 3.2.3 on 2021-06-21 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAR', models.CharField(blank=True, max_length=250, null=True)),
                ('nameEN', models.CharField(blank=True, max_length=250, null=True)),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.company')),
            ],
        ),
    ]
