# Generated by Django 3.2.3 on 2021-06-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0088_costcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='desEN',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
