# Generated by Django 3.2.3 on 2021-06-21 07:44

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0089_costcenter_desen'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationnameAR', models.CharField(blank=True, max_length=300, null=True)),
                ('locationnameEN', models.CharField(blank=True, max_length=300, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('cityAR', models.CharField(blank=True, max_length=300, null=True)),
                ('cityEN', models.CharField(blank=True, max_length=300, null=True)),
                ('streetAR', models.CharField(blank=True, max_length=300, null=True)),
                ('streetEN', models.CharField(blank=True, max_length=300, null=True)),
                ('stateAR', models.CharField(blank=True, max_length=300, null=True)),
                ('stateEN', models.CharField(blank=True, max_length=300, null=True)),
                ('telephone', models.BigIntegerField(blank=True, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=300, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.company')),
            ],
        ),
    ]
