# Generated by Django 3.2.3 on 2021-06-21 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0090_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='documentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleEn', models.CharField(blank=True, max_length=200, null=True)),
                ('titleAr', models.CharField(blank=True, max_length=200, null=True)),
                ('desEn', models.CharField(blank=True, max_length=5000, null=True)),
                ('desAr', models.CharField(blank=True, max_length=5000, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.company')),
            ],
        ),
    ]
