# Generated by Django 3.2.3 on 2021-06-22 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0092_alter_location_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Working_Address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.location'),
        ),
    ]
