# Generated by Django 3.2.3 on 2021-06-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0093_alter_employees_working_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Working_Address',
            field=models.CharField(max_length=250),
        ),
    ]
