# Generated by Django 3.2.3 on 2021-06-22 06:00

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0094_alter_employees_working_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
