# Generated by Django 3.2.3 on 2021-06-22 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0096_auto_20210622_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='ccenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.costcenter'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.employementgrades'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.employementlevel'),
        ),
    ]
