# Generated by Django 3.2.3 on 2021-06-23 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0097_auto_20210622_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='custodytype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enName', models.CharField(blank=True, max_length=200, null=True)),
                ('arName', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.company')),
            ],
        ),
    ]
