# Generated by Django 3.2.3 on 2021-06-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0098_custodytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodytype',
            name='number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
