# Generated by Django 3.2.3 on 2021-06-24 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0100_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='brandModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arName', models.CharField(blank=True, max_length=250, null=True)),
                ('enName', models.CharField(blank=True, max_length=250, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.brands')),
                ('custodytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.custodytype')),
            ],
        ),
    ]
