# Generated by Django 3.2.3 on 2021-06-24 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0101_brandmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.company'),
            preserve_default=False,
        ),
    ]
