# Generated by Django 3.2.3 on 2021-06-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0102_brandmodel_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='isHr',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
