# Generated by Django 3.2.3 on 2021-06-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0103_alter_employees_ishr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='isHr',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='isManager',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
