# Generated by Django 3.2.3 on 2021-06-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0104_auto_20210628_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='fingerusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=50)),
                ('empno', models.CharField(max_length=50)),
                ('fpbiotemplate1', models.CharField(max_length=10000)),
                ('fpbiotemplate2', models.CharField(max_length=10000)),
                ('fno1', models.CharField(max_length=2)),
                ('fno2', models.CharField(max_length=2)),
            ],
        ),
    ]
