# Generated by Django 3.2.3 on 2021-06-30 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0105_fingerusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fingerusers',
        ),
    ]
