# Generated by Django 3.1.4 on 2021-01-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_auto_20210126_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='Remarks',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
