# Generated by Django 3.2.3 on 2021-06-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='Company',
            new_name='company',
        ),
    ]
