# Generated by Django 3.2.11 on 2024-12-11 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AR_Title', models.CharField(blank=True, max_length=200, null=True)),
                ('EN_Title', models.CharField(blank=True, max_length=200, null=True)),
                ('AR_courceInstructions', models.CharField(blank=True, max_length=200, null=True)),
                ('EN_courceInstructions', models.CharField(blank=True, max_length=200, null=True)),
                ('startDate', models.DateField()),
                ('courceDays', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('numberOfSeats', models.IntegerField(blank=True, null=True)),
                ('AR_description', models.CharField(blank=True, max_length=5000, null=True)),
                ('EN_description', models.CharField(blank=True, max_length=5000, null=True)),
                ('address', models.CharField(blank=True, max_length=5000, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.company')),
            ],
        ),
    ]
